// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7D_WEd7oUU3NKW-EgNkK5KGexG4_i_0',
    appId: '1:880264826072:web:ab0461b5c6b801a0715bad',
    messagingSenderId: '880264826072',
    projectId: 'login-c70b6',
    authDomain: 'login-c70b6.firebaseapp.com',
    storageBucket: 'login-c70b6.appspot.com',
    measurementId: 'G-TRZNBZJ10Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Elh0fn7PXZAhrjgZsgeOY-jwwCYx7LY',
    appId: '1:880264826072:android:788a5f817785de11715bad',
    messagingSenderId: '880264826072',
    projectId: 'login-c70b6',
    storageBucket: 'login-c70b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCstuZ_xNsKwpl5hmJRlr7gTZkqSYudQF0',
    appId: '1:880264826072:ios:aa8fd9d99c0dccd3715bad',
    messagingSenderId: '880264826072',
    projectId: 'login-c70b6',
    storageBucket: 'login-c70b6.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCstuZ_xNsKwpl5hmJRlr7gTZkqSYudQF0',
    appId: '1:880264826072:ios:c27b8d695d4156ea715bad',
    messagingSenderId: '880264826072',
    projectId: 'login-c70b6',
    storageBucket: 'login-c70b6.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
